version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - dandywishes_local

  frontend:
    image: dandywishes_frontend:${BUILD_VERSION:-latest}
    environment:
      - NODE_ENV=production
    secrets:
      - supabase_url
      - supabase_key
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:3000/api/healthz"]
        interval: 30s
        timeout: 10s
        retries: 3
        start_period: 40s
    networks:
      - dandywishes_local

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        order: stop-first
        failure_action: rollback
      rollback_config:
        parallelism: 1
        order: stop-first
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/api/status"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - dandywishes_local

networks:
  dandywishes_local:
    driver: overlay

volumes:
  portainer_data:

secrets:
  supabase_url:
    external: true
  supabase_key:
    external: true