version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
    networks:
      - dandywishes_local

  frontend:
    image: dandywishes_frontend:${BUILD_VERSION:-latest}
    environment:
      - NODE_ENV=production
    secrets:
      - supabase_url
      - supabase_key
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        order: start-first
    networks:
      - dandywishes_local

  portainer:
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    networks:
      - dandywishes_local

# Networks
networks:
  dandywishes_local:
    driver: overlay

volumes:
  portainer_data:

secrets:
  supabase_url:
    external: true
  supabase_key:
    external: true